# Generated by Django 3.2.11 on 2022-03-22 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcamstreams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSettings',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webcamstreams.camera')),
                ('stop', models.BooleanField(default=False)),
                ('fps', models.BooleanField(default=False)),
                ('face_detection', models.CharField(choices=[('INACTIVE', 'inactive'), ('SERVER', 'server'), ('CAMERA', 'camera')], default='inactive', max_length=10)),
                ('profile_detection', models.CharField(choices=[('INACTIVE', 'inactive'), ('SERVER', 'server'), ('CAMERA', 'camera')], default='inactive', max_length=10)),
                ('person_detection', models.CharField(choices=[('INACTIVE', 'inactive'), ('SERVER', 'server'), ('CAMERA', 'camera')], default='inactive', max_length=10)),
                ('movement_detection', models.CharField(choices=[('INACTIVE', 'inactive'), ('SERVER', 'server'), ('CAMERA', 'camera')], default='inactive', max_length=10)),
                ('distance_guesser', models.CharField(choices=[('INACTIVE', 'inactive'), ('SERVER', 'server'), ('CAMERA', 'camera')], default='inactive', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='camera',
            name='photoString',
            field=models.TextField(),
        ),
    ]
