# Generated by Django 3.2.11 on 2022-03-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcamstreams', '0003_rename_place_camerasettings_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camera_type',
            field=models.CharField(choices=[('ipcam', 'ipcam'), ('picam', 'raspberry pi camera')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='camera',
            name='photoString',
            field=models.BinaryField(),
        ),
    ]
