# Generated by Django 3.0.5 on 2022-04-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcamstreams', '0005_alter_camera_photostring'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraComsSettings',
            fields=[
                ('Camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webcamstreams.Camera')),
                ('MQTT_broker', models.CharField(default='unknown', max_length=200)),
                ('MQTT_topic', models.CharField(default='unknown', max_length=200)),
                ('discord_webhook', models.CharField(default='unknown', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='camera',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
